# Generated by Django 3.2.25 on 2024-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=300)),
                ('volunteer_phone', models.CharField(max_length=300)),
                ('volunteer_rights', models.CharField(max_length=300)),
                ('volunteer_regime', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
