# Generated by Django 3.2.25 on 2024-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20240331_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=300)),
                ('animal_name', models.CharField(max_length=300)),
                ('animal_age', models.IntegerField()),
                ('animal_sex', models.CharField(choices=[('FE', 'Female'), ('MA', 'Male')], max_length=300)),
                ('animal_admission_date', models.DateField()),
                ('animal_health_status', models.CharField(max_length=300)),
                ('animal_medical_history', models.CharField(max_length=300)),
                ('animal_checkup_date', models.DateField()),
                ('animal_behaviour', models.CharField(max_length=300)),
                ('animal_status', models.CharField(max_length=300)),
                ('animal_notes', models.CharField(max_length=300)),
            ],
        ),
    ]
