# Generated by Django 3.2.25 on 2024-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=300)),
                ('admin_job', models.CharField(choices=[('ACC', 'accountant'), ('HAND', 'handyman'), ('VET', 'vet'), ('SOC', 'socializer'), ('DIR', 'director'), ('COORD', 'volunteer_coordinator'), ('ADOPT', 'adoption_specialist')], max_length=300)),
                ('admin_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_money', models.IntegerField()),
                ('resources_meds', models.IntegerField()),
                ('resources_cat_food', models.IntegerField()),
                ('resources_dog_food', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], max_length=300),
        ),
    ]
