# Generated by Django 3.2.25 on 2024-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_auto_20240331_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('DIR', 'director'), ('SOC', 'socializer'), ('COORD', 'volunteer_coordinator'), ('ACC', 'accountant'), ('VET', 'vet'), ('ADOPT', 'adoption_specialist'), ('HAND', 'handyman')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_sex',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=300),
        ),
    ]
