# Generated by Django 4.2.6 on 2024-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_post_alter_administration_admin_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('DIR', 'director'), ('ADOPT', 'adoption_specialist'), ('VET', 'vet'), ('SOC', 'socializer'), ('COORD', 'volunteer_coordinator'), ('ACC', 'accountant'), ('HAND', 'handyman')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_sex',
            field=models.CharField(choices=[('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кошка', 'Кошка')], max_length=300),
        ),
    ]
