# Generated by Django 4.2.6 on 2024-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0008_alter_administration_admin_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('ACC', 'accountant'), ('SOC', 'socializer'), ('ADOPT', 'adoption_specialist'), ('HAND', 'handyman'), ('VET', 'vet'), ('COORD', 'volunteer_coordinator'), ('DIR', 'director')], max_length=300),
        ),
    ]
