# Generated by Django 4.2.6 on 2024-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0009_person_alter_administration_admin_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('HAND', 'handyman'), ('DIR', 'director'), ('ACC', 'accountant'), ('COORD', 'volunteer_coordinator'), ('SOC', 'socializer'), ('VET', 'vet'), ('ADOPT', 'adoption_specialist')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_sex',
            field=models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака')], max_length=300),
        ),
    ]
