# Generated by Django 4.2.6 on 2024-04-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0010_alter_administration_admin_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_admission_date',
            new_name='admission_date',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_behaviour',
            new_name='behaviour',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_checkup_date',
            new_name='checkup_date',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_health_status',
            new_name='health_status',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_medical_history',
            new_name='medical_history',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_sex',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_weight',
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кошка', 'Кошка')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('DIR', 'director'), ('HAND', 'handyman'), ('ACC', 'accountant'), ('SOC', 'socializer'), ('VET', 'vet'), ('ADOPT', 'adoption_specialist'), ('COORD', 'volunteer_coordinator')], max_length=300),
        ),
    ]
