# Generated by Django 4.2.6 on 2024-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0011_delete_person_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='type',
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('DIR', 'director'), ('ACC', 'accountant'), ('COORD', 'volunteer_coordinator'), ('SOC', 'socializer'), ('ADOPT', 'adoption_specialist'), ('HAND', 'handyman'), ('VET', 'vet')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=300),
        ),
    ]
