# Generated by Django 4.2.6 on 2024-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0013_alter_administration_admin_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('VET', 'vet'), ('ADOPT', 'adoption_specialist'), ('SOC', 'socializer'), ('COORD', 'volunteer_coordinator'), ('HAND', 'handyman'), ('DIR', 'director'), ('ACC', 'accountant')], max_length=300),
        ),
    ]
