# Generated by Django 4.2.6 on 2024-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0014_alter_administration_admin_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('COORD', 'volunteer_coordinator'), ('VET', 'vet'), ('ACC', 'accountant'), ('SOC', 'socializer'), ('DIR', 'director'), ('ADOPT', 'adoption_specialist'), ('HAND', 'handyman')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='behaviour',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='checkup_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='medical_history',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
