# Generated by Django 4.2.6 on 2024-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0015_alter_administration_admin_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='admin_job',
            field=models.CharField(choices=[('DIR', 'director'), ('HAND', 'handyman'), ('VET', 'vet'), ('COORD', 'volunteer_coordinator'), ('ADOPT', 'adoption_specialist'), ('SOC', 'socializer'), ('ACC', 'accountant')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='behaviour',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='medical_history',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='notes',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кошка', 'Кошка')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
