# Generated by Django 4.2.6 on 2024-04-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0017_alter_administration_admin_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='admin_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='admin_salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_regime',
            new_name='regime',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_rights',
            new_name='rights',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='admin_job',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resources_cat_food',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resources_dog_food',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resources_meds',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resources_money',
        ),
        migrations.AddField(
            model_name='administration',
            name='job',
            field=models.CharField(choices=[('COORD', 'volunteer_coordinator'), ('SOC', 'socializer'), ('ACC', 'accountant'), ('ADOPT', 'adoption_specialist'), ('DIR', 'director'), ('VET', 'vet'), ('HAND', 'handyman')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='cat_food',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='dog_food',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='meds',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='money',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Девочка', 'Мальчик'), ('Девочка', 'Девочка')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
