# Generated by Django 4.2.6 on 2024-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0018_person_rename_admin_name_administration_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='administration',
            name='job',
            field=models.CharField(choices=[('ADOPT', 'adoption_specialist'), ('HAND', 'handyman'), ('SOC', 'socializer'), ('DIR', 'director'), ('VET', 'vet'), ('ACC', 'accountant'), ('COORD', 'volunteer_coordinator')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Девочка', 'Девочка'), ('Девочка', 'Мальчик')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кошка', 'Кошка')], max_length=300),
        ),
    ]
