# Generated by Django 4.2.6 on 2024-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0019_delete_person_alter_administration_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='job',
            field=models.CharField(choices=[('Ветеринар', 'Ветеринар'), ('Специалист по усыновлению', 'Специалист по усыновлению'), ('Бухгалтер', 'Бухгалтер'), ('Социализатор', 'Социализатор'), ('Директор', 'Директор'), ('Разнорабочий', 'Разнорабочий'), ('Координатор волонеров', 'Координатор волонеров')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
