# Generated by Django 4.2.6 on 2024-04-24 16:07

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0024_alter_administration_job_alter_animal_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='job',
            field=models.CharField(choices=[('Специалист по усыновлению', 'Специалист по усыновлению'), ('Бухгалтер', 'Бухгалтер'), ('Разнорабочий', 'Разнорабочий'), ('Координатор волонеров', 'Координатор волонеров'), ('Директор', 'Директор'), ('Социализатор', 'Социализатор'), ('Ветеринар', 'Ветеринар')], max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака')], max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=11),
        ),
    ]
